// <auto-generated />
using System;
using DiaryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241006055819_AddedSeedingDataDiaryEntries")]
    partial class AddedSeedingDataDiaryEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryProject.Models.DiaryEntries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 10, 6, 1, 58, 19, 106, DateTimeKind.Local).AddTicks(1137),
                            Entry = "I went snowboarding today and it was awesome!",
                            Title = "Went snowboarding"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 10, 6, 1, 58, 19, 106, DateTimeKind.Local).AddTicks(1181),
                            Entry = "I went to the beach today and it was awesome!",
                            Title = "Went to the beach"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 10, 6, 1, 58, 19, 106, DateTimeKind.Local).AddTicks(1183),
                            Entry = "I went to the movies today and it was awesome!",
                            Title = "Went to the movies"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
